name:                sway
version:             0.1.0.0
github:              "quytelda/haskell-sway"
license:             BSD3
author:              "Quytelda Kahja"
maintainer:          "quytelda@tamalin.org"
copyright:           "Copyright 2023 Quytelda Kahja"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/quytelda/sway#readme>

dependencies:
- aeson >= 1.5 && < 3
- base >= 4.7 && < 5
- binary >= 0.8
- bytestring >= 0.10
- containers >= 0.6.4 && < 0.7
- mtl >= 2.2 && < 3
- network >= 3.1 && < 4
- transformers >= 0.5
- vector >= 0.12

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  sway-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sway
    - hspec >= 2.7 && < 3
